check_task:
  container:
    image: fnichol/check-shell
  check_script: make check

docker_builder:
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - check
  env:
    IMAGE_NAME: fnichol/check-shell
    DOCKER_USERNAME: user
    DOCKER_PASSWORD: pass
  build_script: ./build.sh "$IMAGE_NAME" "$CIRRUS_TAG" latest
  login_script: >
    echo "$DOCKER_PASSWORD"
      | docker login --username "$DOCKER_USERNAME" --password-stdin
  push_script:
    - docker push "$IMAGE_NAME:$CIRRUS_TAG"
    - docker push "$IMAGE_NAME:latest"
